### ISSUE TITLE
Dynamic Param

### ISSUE THREAD

**Issue by dotps1** [Crypt32/PsCmdletHelpEditor#1]
I have been using this tool for a while, however the version from CodePlex.  When I import in a module I that has dynamic parameters, I cannot seem to manually add them, and the program does not see them.

Now, this may not be an issue since you have started working on it.  On that note, can you add a build of your project?  I don't have VS installed, so I cannot build it with that, maybe there is another way?

thanks.

**Comment by Crypt32** [comment]
What kind of dynamic parameter? The editor retrieves parameters which are listed in the `Get-Command` cmdlet output.

**Comment by dotps1** [comment]
so, the syntax goes like this:

```powershell
Function Foo-Bar {
    Param()
    DynamicParam {
        # Stuff Goes here to justify if the parameter exists or not.
    }
}
```

IE, Get-Item, Get-ChildItem, Get-Content all have dynamic parameters based on the provider that is being accessed, IE FileSystem, Registry.

**Comment by Crypt32** [comment]
I can't promise anything at this point. The editor definitely requires a number of enhancements, however it requires a lot of research to get a not so crappy design. Currently, I'm in a process of significant code rewrite to make the exitisting code more reliable and only then will be able to think about this.

**Comment by dotps1** [comment]
no worries, I forked the code, I am going to take a look and see what I can do.  thanks.

**Comment by dotps1** [comment]
so, I was playing around a little, and getting the dynamic params of a function is actually pretty easy.  For example in this cmdlet I have written called [New-Gist](https://github.com/dotps1/PSGist/blob/master/PSGist/Public/New-Gist.ps1) it has two dynamic params, 'IseScriptPane', and 'FileName' and with this chunk of code I can get those from the param sets:

```powershell
Get-Command -Name New-Gist | Select -ExpandProperty Parameters | Select -ExpandProperty Values | ? IsDynamic -eq $true
```

And it returns the two dynamic params:

```
Name            : IseScriptPane
ParameterType   : System.Management.Automation.SwitchParameter
ParameterSets   : {[IseScriptPane, System.Management.Automation.ParameterSetMetadata]}
IsDynamic       : True
Aliases         : {}
Attributes      : {IseScriptPane}
SwitchParameter : True

Name            : FileName
ParameterType   : System.String
ParameterSets   : {[IseScriptPane, System.Management.Automation.ParameterSetMetadata]}
IsDynamic       : True
Aliases         : {}
Attributes      : {IseScriptPane}
SwitchParameter : False
```

not sure if it helps you, but the properites are there on the parameter objects.

**Comment by Crypt32** [comment]
I do literally the same thing (query command metadata throught Get-Command cmdlet) and wonder why it is not populated.

**Comment by dotps1** [comment]
huh, yeah that is very strange then.

**Comment by dotps1** [comment]
this just had to do with me running it from the shell vs the ISE, the param was only exposed in the ise.

**Comment by Crypt32** [comment]
Just to clarify: should the parameter appear in editor or not?
